language: java

script:
  - mvn test -B -Dmatsim.preferLocalDtds=true
  - mvn deploy -DskipTests=true --settings=settings.xml
#  - if ! [[ $( cat pom.xml | grep "SNAPSHOT" ) ]]; then mvn deploy -DskipTests=true --settings=settings.xml; fi
